### ISSUE TITLE
Fails to parse certain PDFs, failing looking for "xref".

### ISSUE THREAD

**Issue by jaccarmac** [mbattyani/cl-pdf#11]
Haven't dug in real deep yet, but it's hitting a stream of bytes `#\3 #\2 #\8 #\  #\o` when `#\x #\r #\e #\f` followed by some integer is expected.

**Comment by jaccarmac** [comment]
This is simply the parser not dealing with compressed PDFs, and a silly question based on not understanding the format. I'll work on a PR to provide decompression during parse-time.

**Comment by ntrocado** [comment]
I'm having the exact same problem. Did you find a solution? I'm afraid I don't really understand how the parser in cl-pdf deals with compression.

**Comment by jaccarmac** [comment]
This is something I've had on my TODO list for a year+ now I guess, but not at high enough priority to dive into the code. I'm also poorly versed in CL and PDF internals. Based on my skimming from last year, it seems that the lib only implements the compression one way, but I never got around to starting a patch to add decompression properly. If you have any ideas you're more than welcome to share them and I may take a look again.

**Comment by ntrocado** [comment]
Thanks! For now and for my use case I'm starting by decompressing the files with a third party utility, but I'll look more into this when I have the time (which means it's planted on my todo list as well now...).

**Comment by jaccarmac** [comment]
May I ask which utility? That might solve the original purpose of using `cl-pdf`, come to think of it...

**Comment by ntrocado** [comment]
I'm just using one of the online pdf processing sites...
