### ISSUE TITLE
Specialize PDF-PARSE-ERROR

### ISSUE THREAD

**Issue by phoe** [mbattyani/cl-pdf#18]
Currently the code for CL-PDF defines a root error class named `pdf-parse-error` and uses it in multiple distinct contexts, only passing different message arguments to it. It might be better to create specialized subtypes of this error type, export their names and accessors, and use them throughout `pdf-parser.lisp`.

**Comment by adlai** [comment]
@phoe please close this issue, unless #19 is not sufficient.

**Comment by phoe** [comment]
Oh! I wasn't aware of #19 - yes, it sounds good. Thank you!

**Comment by adlai** [comment]
[Here are found some examples](https://en.wikipedia.org/wiki/PDF/UA#Requirements_for_conforming_PDF_files_(Clause_7)) that can help when sketching out the conditions that should always be signalled by the parser, although might not be considered errors if the document is going directly to print.
