### ISSUE TITLE
Parse PDF

### ISSUE THREAD

**Issue by ertpoi** [mbattyani/cl-pdf#20]
Does CL-PDF also parse PDF files, so from PS to CL objects or something like that?

**Comment by adlai** [comment]
There is a parser that is not included in the main ASDF system; it parses according to the PDF 1.4 specification and builds CL objects corresponding to the document's structure.

**Comment by adlai** [comment]
@ertpoi did I answer your question?

**Comment by ertpoi** [comment]
Yes, thank you (and sorry for the delay!)

**Comment by mbattyani** [comment]
I guess I'm the worst for the delays. I should try and wake up from my covid torpor.
Thanks @adlai for the answer
